//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_MINI_PROJECT_SCAFFOLDING.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMSContext : DbContext
    {
        public EMSContext()
            : base("name=EMSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department_174778> Department_174778 { get; set; }
        public virtual DbSet<User_Master_174778> User_Master_174778 { get; set; }
        public virtual DbSet<Employee_174778> Employee_174778 { get; set; }
        public virtual DbSet<Grade_Master_174778> Grade_Master_174778 { get; set; }
    }
}
