//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_MINI_PROJECT_SCAFFOLDING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Master_174778
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grade_Master_174778()
        {
            this.Employee_174778 = new HashSet<Employee_174778>();
        }
    
        public string Grade_Code { get; set; }
        public string Description { get; set; }
        public int Min_Salary { get; set; }
        public int Max_Salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_174778> Employee_174778 { get; set; }
    }
}
